apiVersion: v1
kind: Secret
metadata:
  name: payhere-credentials
type: Opaque
stringData:
  PAYHERE_MERCHANT_ID: "CHANGE_ME_PAYHERE_MERCHANT_ID"
  PAYHERE_MERCHANT_SECRET: "CHANGE_ME_PAYHERE_MERCHANT_SECRET"
