apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: docapp/api-gateway:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "4000"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:4001"
            - name: DOCTOR_SERVICE_URL
              value: "http://doctor-management-service:4002"
            - name: APPOINTMENT_SERVICE_URL
              value: "http://appointment-service:4003"
            - name: PAYMENT_SERVICE_URL
              value: "http://payment-service:4006"
            - name: TELEMEDICINE_SERVICE_URL
              value: "http://telemedicine:4010"
            - name: LOG_LEVEL
              value: "info"

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
