apiVersion: v1
kind: Secret
metadata:
  name: patient-cloudinary-secret
type: Opaque
stringData:
  CLOUDINARY_NAME: "CHANGE_ME_CLOUDINARY_CLOUD_NAME"
  CLOUDINARY_API_KEY: "CHANGE_ME_CLOUDINARY_API_KEY"
  CLOUDINARY_API_SECRET: "CHANGE_ME_CLOUDINARY_API_SECRET"
