apiVersion: v1
kind: Secret
metadata:
  name: notification-db-secret
type: Opaque
stringData:
  PGPASSWORD: "postgres"
  RESEND_API_KEY: "re_JuzofU1d_DMkH9kcC8kwyzCi1kD1E2xnh"
  RESEND_FROM_EMAIL: "onboarding@resend.dev"
  TWILIO_ACCOUNT_SID: "ACca07e6dfda6cb577f67c96bc49f12114"
  TWILIO_AUTH_TOKEN: "e24fd4fa798b630ef3c7d62ae31f9652"
  TWILIO_PHONE_NUMBER: "+13185912428"
