apiVersion: v1
kind: Secret
metadata:
  name: notification-db-secret
type: Opaque
stringData:
  PGPASSWORD: "postgres"
  RESEND_API_KEY: "re_JuzofU1d_DMkH9kcC8kwyzCi1kD1E2xnh"
  RESEND_FROM_EMAIL: "onboarding@resend.dev"
  TWILIO_ACCOUNT_SID: "ACca07e6dfda6cb577f67c96bc49f12114"
  TWILIO_AUTH_TOKEN: "18c049c1b3ae9b3e9a379aeeaa2f3e17"
  TWILIO_PHONE_NUMBER: "+13185912428"