apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: docapp/notification-service:local
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "6000"
            - name: TZ
              value: "Asia/Colombo"
            - name: PGHOST
              value: "notification-postgres"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: notification-db-config
                  key: PGDATABASE
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: notification-db-config
                  key: PGUSER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: PGPASSWORD
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: RESEND_API_KEY
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: notification-db-secret
                  key: TWILIO_PHONE_NUMBER

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: LoadBalancer
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
